### ISSUE TITLE
Add missing instructions for using Domite as a library.

### ISSUE THREAD

**Issue by hhzl** [amber-smalltalk/amber-contrib-domite#18]
The README gives the following steps on what to do to use ``Domite`` as a library

- Install Amber (Instructions)
- Do ``amber init``
- bower install domite --save
- Start server with amber serve and go to http://localhost:4000/ 

is incomplete. 

Which action is needed to make the package appear in the category list?

- Install Amber (Instructions)
- Do ``amber init``
- bower install domite --save
- ???
- Start server with amber serve and go to http://localhost:4000/ 
- ???

**Comment by herby** [comment]
Should be fixed by  ea03add.

**Comment by hhzl** [comment]
Thanks so far for the additional clarification.

 Which expression do I need to add to the ``import:`` section of the package which is going to use ``Domite``.

Assuming my package which wants to use ``Domite``  is called ``Atest`` then

````
Package
	named: 'Atest'
	imports: {'amber-contrib-domite'}
	transport: (AmdPackageTransport namespace: 'amber-atest')
````

did not work.

**Comment by herby** [comment]
I am pretty unhappy from this. If that is so hard to grasp, then whole work on amber is complete vain. If no-one can understand that each package is AMD module and each AMD module has its id (and .amd.json files map these ids or path prefixes if they are in form of 'path/leaf-id' to actual location) which is actually used to load it, then no-one will ever be able to compose more libraries into any app.

Hannes Hirzel wrote:
> Thanks so far for the additional clarification.
>
> Which expression do I need to add to the |import:| section of the 
> package which is going to use |Domite|.
>
> Assuming my package which wants to use |Domite| is called |Atest| then
>
> |Package
>      named: 'Atest'
>      imports: {'amber-contrib-domite'}

Of course not this. :-\ This is not an AMD module id nor ultimately part of it.

>      transport: (AmdPackageTransport namespace: 'amber-atest')
> |
>
> did not work.

**Comment by hhzl** [comment]
Thank you for the clarification. The AMD module name is defined here

https://github.com/amber-smalltalk/amber-contrib-domite/blob/master/local.amd.json

**Comment by herby** [comment]
Not really, there's just the paths mapping (the "map" section is to be ignored, it's just the helper for migration from old names to new names).

AMD module id is either hardcoded in define call or derived from filename and symbolic path used to get there.

What's more important, these id are used in list of dependencies in define call or list of package to load in require call. The whole thing about namespaces is about these dependencies having stable names, as is I believe written in some faq or wiki page.

Nevertheless, when users are unwilling to learn hard what is AMD module, id, mapping path prefix and fact that namespace is that name prefix, there's really no point.

Hannes Hirzel wrote:
> Thank you for the clarification. The AMD module name is defined here
>
> https://github.com/amber-smalltalk/amber-contrib-domite/blob/master/local.amd.json
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/amber-smalltalk/amber-contrib-domite/issues/1
8#issuecomment-91674208>.
>

**Comment by hhzl** [comment]
Yes, as you mentionded the JavaScript ``define`` command gave me the clue.

I went to 
https://github.com/amber-smalltalk/amber-contrib-domite/blob/master/src/DOMite.js

to pick the name from the first line which is

````
 define("amber/domite/DOMite", ["amber/boot", "amber_core/Kernel-Collections"], function($boot){
````.

So what I did in Helios

````
Package
	named: 'Atest'
	imports: {'amber/domite/DOMite'}
	transport: (AmdPackageTransport namespace: 'amber-atest')
````

**AND** there was an additional obstacle. Just adding the ``imports:``  parameter was not enough to mark the package as changed. I had to  change a method to mark the package as changed so that I could commit it.

This happened earlier today and was an additional obstacle.

**Comment by herby** [comment]
You can commit any time. I just change the `imports:` section, save and commit by hand (Ctrl+space, k).

The fact that helios does not change the state to dirty when changing package template is known bug and is filed in the tracker (just, it still does not have a fix).

**Comment by hhzl** [comment]
Thank you.
